name: Maven CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
            
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: microsoft

    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2      

    - name: Build and test project with Maven
      run: mvn -B package --file pom.xml

    
  publish-job:
      runs-on: ubuntu-latest
      needs: [build_and_test]
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: microsoft
            

        - name: Extract Maven project version
          run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"   >> $GITHUB_OUTPUT
          id: project

        - name: Show extracted Maven project version
          run: echo ${{ steps.project.outputs.version }}

        - run: mvn -B package --file pom.xml -DskipTests
        - uses: actions/upload-artifact@v3
          with:
            name: kafka-connect-transform-record2jsonstring-${{ steps.project.outputs.version }}-with-dependencies
            path: ./target/kafka-tojsonstring-smt/kafka-connect-transform-record2jsonstring-${{ steps.project.outputs.version }}-jar-with-dependencies.jar
